my_blog/blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import IndexView, DetailView, ArticleCreateView, test
# from .views import (IndexView, DetailView)#, DetailView, CategoryView, TagView, AboutView,
                    #SilianView, MySearchView, ArchiveView, TimelineView)

app_name = 'blog'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('blog/', IndexView.as_view(), name='index'),
    path('article/<slug:slug>/', DetailView.as_view(), name='detail'),  # 文章内容页
    path('article-create/', ArticleCreateView.as_view(), name='article_create'), #新建文章
    path('test/',test,name='test'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls',namespace='blog')),#主页路由
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'), # 网站地图
]

my_blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class Category(models.Model):
    '''文章分类'''
    name = models.CharField(max_length=200)

    class Meta:
        '''定义模型的一些属性'''
        verbose_name = '分类' # 中文名
        verbose_name_plural = verbose_name # 复数形式
        ordering = ['name'] # 排序依据

    def __str__(self):
        '''返回模型的信息'''
        return self.name

class Tag(models.Model):
    '''文章标签'''
    name = models.CharField(max_length=100)

    class Meta:
        '''定义模型的一些属性'''
        verbose_name = '标签' # 中文名
        verbose_name_plural = verbose_name # 复数形式
        ordering = ['name'] # 排序依据

    def __str__(self):
        '''返回模型的信息'''
        return self.name

class Article(models.Model):
    '''文章模型，储存文章内容'''
    title = models.CharField(max_length=200) # 文章标题
    body = models.TextField('正文')                # 正文

    slug = models.SlugField(unique=True)    # 文章url
    create_date = models.DateTimeField(default=timezone.now)    # 创建时间
    modify_date = models.DateTimeField(auto_now=True)   # 修改时间

    summary = models.TextField('摘要', max_length=400, blank=True)# 摘要，可以为空
    category = models.ForeignKey(Category, on_delete=models.CASCADE) # 分类和标签
    tags = models.ManyToManyField(Tag, blank=True)
    views = models.IntegerField('阅览量', default=0)

    author = models.ForeignKey(User, verbose_name='作者',on_delete=models.CASCADE)   # 作者

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        '''如果有摘要则显示摘要，否则显示文章前50个字'''
        if len(self.summary):
            return self.summary
        else:
            return self.body[:50]+'...'

    def update_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_pre(self):
        return Article.objects.filter(id__lt=self.id).order_by('-id').first()

    def get_next(self):
        return Article.objects.filter(id__gt=self.id).order_by('id').first()

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug':self.slug})

# 首页轮播
class Carousel(models.Model):
    number = models.IntegerField('编号', help_text='编号决定图片播放的顺序，图片不要多于5张')
    title = models.CharField('标题', max_length=20, blank=True, null=True, help_text='标题可以为空')
    content = models.CharField('描述', max_length=80)
    img_url = models.CharField('图片地址', max_length=200)
    url = models.CharField('跳转链接', max_length=200, default='#', help_text='图片跳转的超链接，默认#表示不跳转')

    class Meta:
        verbose_name = '图片轮播'
        verbose_name_plural = verbose_name
        # 编号越小越靠前，添加的时间约晚约靠前
        ordering = ['number', '-id']

    def __str__(self):
        return self.content[:25]

# 友情链接
class FriendLink(models.Model):
    name = models.CharField('网站名称', max_length=50)
    description = models.CharField('网站描述', max_length=100, blank=True)
    link = models.URLField('友链地址', help_text='请填写http或https开头的完整形式地址')
    logo = models.URLField('网站LOGO', help_text='请填写http或https开头的完整形式地址', blank=True)
    create_date = models.DateTimeField('创建时间', auto_now_add=True)
    is_active = models.BooleanField('是否有效', default=True)
    is_show = models.BooleanField('是否首页展示', default=False)

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name
        ordering = ['create_date']

    def __str__(self):
        return self.name

    def get_home_url(self):
        '''提取友链的主页'''
        u = re.findall(r'(http|https://.*?)/.*?', self.link)
        home_url = u[0] if u else self.link
        return home_url

    def active_to_false(self):
        self.is_active = False
        self.save(update_fields=['is_active'])

    def show_to_false(self):
        self.is_show = True
        self.save(update_fields=['is_show'])

my_blog/blog/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import Article

# 写文章的表单类
class ArticleForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = Article
        # 定义表单包含的字段
        fields = ['title', 'slug', 'category', 'tags', 'body']

my_blog/blog/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.utils.text import slugify
from django.shortcuts import get_object_or_404, get_list_or_404
from .models import Article, Category, Tag
from django.core.cache import cache
from .forms import ArticleForm
# 引入HttpResponse
from django.http import HttpResponse
# 引入login装饰器
from django.contrib.auth.decorators import login_required

from markdown.extensions.toc import TocExtension  # 锚点的拓展
import markdown
import time, datetime

# Create your views here.
class IndexView(generic.ListView):
    """
        首页视图,继承自ListVIew，用于展示从数据库中获取的文章列表
    """
    # 获取数据库中的文章列表
    model = Article
    # template_name属性用于指定使用哪个模板进行渲染
    template_name = 'blog/index.html'
    # context_object_name属性用于给上下文变量取名（在模板中使用该名字）
    context_object_name = 'articles'

class DetailView(generic.DetailView):
    model = Article
    template_name = 'blog/detail.html'
    context_object_name = 'article'

    def get_object(self):
        obj = super(DetailView, self).get_object()
        # 设置浏览量增加时间判断,同一篇文章两次浏览超过半小时才重新统计阅览量,作者浏览忽略
        u = self.request.user
        ses = self.request.session
        the_key = 'is_read_{}'.format(obj.id)
        is_read_time = ses.get(the_key)
        if u != obj.author:
            if not is_read_time:
                obj.update_views()
                ses[the_key] = time.time()
            else:
                now_time = time.time()
                t = now_time - is_read_time
                if t > 60 * 30:
                    obj.update_views()
                    ses[the_key] = time.time()
        # 获取文章更新的时间，判断是否从缓存中取文章的markdown,可以避免每次都转换
        '''
        ud = obj.modify_date.strftime("%Y%m%d%H%M%S")
        md_key = '{}_md_{}'.format(obj.id, ud)
        cache_md = cache.get(md_key)
        if cache_md:
            obj.body, obj.toc = cache_md
        else:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                'pymdownx.arithmatex',
                #'markdown.extensions.toc',
                TocExtension(slugify=slugify),
            ])
            obj.body = md.convert(obj.body)
            obj.toc = md.toc
            cache.set(md_key, (obj.body, obj.toc), 60 * 60 * 12)
            '''
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.fenced_code',
            'mdx_math',
            TocExtension(slugify=slugify),
            ])
        obj.body = md.convert(obj.body)
        obj.toc = md.toc
        return obj

# 写文章的视图
class ArticleCreateView(generic.edit.CreateView):
    # 要使用的数据模型
    model = Article
    # 要填写的字段
    form_class = ArticleForm
    # 要使用的模板,默认为article_form.html
    tags = Tag.objects.all()
    categories = Category.objects.all()
    template_name = 'blog/article_create.html'
    context_object_name = 'articles'

    def get(self,request, *args, **kwargs):
        # 请求新建文章，创建表单类实例
        # 向模板提供数据
        context = {'categories': self.categories,'tags':self.tags}
        # 返回模板
        return render(request, 'blog/article_create.html', context)

    def post(self,request,*args, **kwargs):
        # 提交文章
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        # Verify form is valid
        if form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = form.save(commit=False)
            new_article.author = self.request.user
            #new_article.tags = Article.objects.get(id=request.POST['tags'])
            #new_article.category = Article.objects.get(id=request.POST['category'])
            # 将新文章保存到数据库中
            new_article.save()
            form.save_m2m()
            # 完成后返回到文章列表
            #messages.success(request, 'Item created successfully!')
            return redirect("blog:index")
        # 如果数据不合法，返回错误信息
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        #
        model = form.save(commit=False)
        model.author = self.request.user
        model.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self,form):
        #
        self.object = None
        return HttpResponse("表单内容有误，请重新填写。")

    def get_success_url(self):
        return reverse('createview')

# s测试页面
def test(request):
    return render(request, 'blog/test.html')

my_blog/blog/templates/blog/article_create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "blog/base.html" %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action="." enctype="multipart/form-data">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}

                <!-- 文章标题图 -->
                <div class="form-group">
                    <label for="avatar">标题图</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>

                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text"
                           class="form-control"
                           id="title"
                           name="title"
                    >
                </div>

                <!-- 文章分类 -->
                <div class="form-group">
                    <label for="category">分类</label>
                    <select class="form-control col-3"
                            id="category"
                            name="category"
                    >
                            <option value="none">请选择分类..</option>
                        {% for category in categories %}
                            <option value="{{ category.id }}">{{ category }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="tags">标签</label>
                    <select class="form-control col-3"
                            id="column"
                            name="column"
                    >
                            <option value="none">请选择标签..</option>
                        {% for tag in tags %}
                            <option value="{{ tag.id }}">{{ tag }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- slug -->
                <div class="form-group">
                  <!-- 标签 -->
                  <label for="slug">slug</label>
                  <!-- 文本框 -->
                  <input type="text"
                         class="form-control col-3"
                         id="slug"
                         name="slug"
                  >
                </div>

                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text"
                              class="form-control"
                              id="body"
                              name="body"
                              rows="12"
                    ></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

my_blog/blog/templates/blog/base.html
<!DOCTYPE html>
<!-- 载入静态文件 -->
{% load static %}
<!-- 网站主语言 -->
<html lang="zh-cn" style="height: 100%;">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!--markdown语法支持-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css" crossorigin="anonymous">
    <!--LaTeX支持-->
    <script src="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/katex/dist/contrib/mathtex-script-type.min.js" defer></script>
    <!--代码高亮-->
    <link rel="stylesheet" href="/static/blog/css/vim.css">
</head>

<body style="min-height: 100%;display: flex;flex-direction: column;">
    <!-- 引入导航栏 -->
    {% include 'blog/header.html' %}
    <!-- 预留具体页面的位置 -->
  <div style="flex:1">
    {% block content %}{% endblock content %}
    <!--回到顶部按钮-->
    <div class="text-center" id="to-top">
        <i class="fa fa-chevron-up" id="btn-top" title="回到顶部"></i>
    </div>
    <!-- 引入注脚 -->
  </div>
    {% include 'blog/footer.html' %}
    <!--LaTeX支持-->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

</html>

my_blog/blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% load static %}

{% block title %}文章详情{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- 展示文章的title -->
        <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
        <!-- 展示文章的author -->
        <div class="col-12 alert alert-success">作者：{{ article.author }}</div>
        <!-- 文章正文 -->
        <div class="col-12">
            <p>{{ article.body|safe }}</p>
        </div>
    </div>
</div>
{% endblock content %}

my_blog/blog/templates/blog/detail_new.html
{% extends 'blog/base.html' %}
{% load blog_tags static %}
{% load humanize %}

{% block head_title %}{{ article.title }}_{{ article.category }}{% endblock %}
{% block metas %}
<meta name="description" content="{{ article.summary }}">
<meta name="keywords" content="{% keywords_to_str article %}">
{% endblock %}


{% block top-file %}
{% if user.is_authenticated %}
<link href="https://cdn.bootcss.com/simplemde/1.11.2/simplemde.min.css" rel="stylesheet">
{% endif %}
<link href="{% static 'blog/css/detail.css' %}?v=20190918.07" rel="stylesheet">
<link href="{% static 'blog/css/monokai.css' %}?v=20190910.2" rel="stylesheet">
<link href="{% static 'comment/css/base_comment.css' %}?v=20190114.554" rel="stylesheet">
{% endblock %}

{% block base_content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-9 col-xl-10">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb bg-white border-0 rounded-0 mb-2 py-2 f-15">
                    <li class="breadcrumb-item">
                        <i class="fa fa-home mr-1"></i><a href="{% url 'blog:index' %}">首页</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{{ article.category.get_absolute_url }}">{{ article.category}}</a>
                    </li>
                    <li class="breadcrumb-item active d-none d-md-block" aria-current="page">{{ article.title }}</li>
                    <li class="breadcrumb-item active d-md-none" aria-current="page">当前位置</li>
                </ol>
            </nav>
            <div class="card rounded-0 border-0" id="article">
                <div class="card-body px-2 px-md-3 pb-0">
                    <h1 class="card-title text-center font-weight-bold text-info">{{ article.title }}</h1>
                    <hr>
                    <div class="text-center f-13">
                        <span class="mx-2" data-toggle="tooltip" data-placement="bottom"
                              title="最后编辑于{{ article.modify_date|date:'Y年m月d日' }}">{{ article.create_date }}</span>
                        <span class="mx-2">阅读 {{ article.views }}</span>
                        <!--
                        <a class="mx-2 to-com" href="#comment-block">评论  get_comment_count article %}</a>
                        -->
                    </div>
                    <div class="article-body mt-4 f-17" style="line-height:1.8">
                        {{ article.body|safe }}
                        <blockquote class="p-1 f-14" style="border-left: 4px solid #dc3545;">
                            <p class="m-1"><strong>版权声明：</strong>如无特殊说明，文章均为本站原创，转载请注明出处</p>
                            <p class="m-1"><strong>本文链接：</strong>{{ site_url }}{{ article.get_absolute_url }}</p>
                        </blockquote>
                    </div>
                    <div class="tag-cloud my-4">
                        {% for tag in article.tags.all %}
                        <a class="tags f-16" href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                    <nav class="more-page f-16">
                        <ul class="pagination justify-content-between">
                            <li class="page-item">
                                {% if article.get_pre %}
                                <a class="d-none d-md-block" href="{{ article.get_pre.get_absolute_url }}"
                                   title="上一篇：{{ article.get_pre.title }}">
                                    <i class="fa fa-chevron-left mr-1"></i>
                                    {{ article.get_pre.title|truncatechars:18 }}
                                </a>
                                <a class="d-md-none" href="{{ article.get_pre.get_absolute_url }}">
                                    <i class="fa fa-chevron-left mr-1"></i>上一篇</a>
                                {% endif %}
                            </li>
                            <li class="page-item">
                                {% if article.get_next %}
                                <a class="d-none d-md-block" href="{{ article.get_next.get_absolute_url }}"
                                   title="下一篇：{{ article.get_next.title }}">
                                    {{ article.get_next.title|truncatechars:18 }}
                                    <i class="fa fa-chevron-right ml-1"></i>
                                </a>
                                <a class="d-md-none" href="{{ article.get_next.get_absolute_url }}">
                                    下一篇<i class="fa fa-chevron-right ml-1"></i>
                                </a>
                                {% endif %}
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!--
            <div class="card mt-2 rounded-0 border-0" id="comment-block">
                {% include 'comment/comment_form.html' %}
                 get_parent_comments article as comment_list %}
                {% include 'comment/comment_list.html' %}
            </div>
            -->
        </div>
    </div>
</div>
<!--图片预览-->
<div class="modal fade" id="img-to-big" tabindex="-1" role="dialog" aria-labelledby="img-to-bigTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document" style="max-width: 90%">
        <img class="rounded mx-auto d-block" alt="image" style="max-width: 100%">
    </div>
</div>
<!--前后文章-->
{% if article.get_pre %}
<div class="more-blog" id="icon-pre-blog">
    <a href="{{ article.get_pre.get_absolute_url }}">
        <i class="fa fa-angle-left fa-3x"></i>
    </a>
</div>
{% endif %}
{% if article.get_next %}
<div class="more-blog" id="icon-next-blog">
    <a href="{{ article.get_next.get_absolute_url }}">
        <i class="fa fa-angle-right fa-3x"></i>
    </a>
</div>
{% endif %}
{% endblock %}

{% block end_file %}

{% endblock %}

my_blog/blog/templates/blog/footer.html
<div>
    <br><br><br>
</div>

  <footer id="footer" class="container-fluid mt-4 py-0 bg-dark" >
  <div class="text-white">

    <div class="card-body text-center px-0 f-16">
        <p class="card-text mb-1">Copyright&nbsp;&copy;&nbsp;<span id="year-info"></span>
            <a href="https://github.com/JabinHao" target="_blank" title="博客作者的Github">JabinHao</a>&nbsp;Powered&nbsp;by&nbsp;Django.
        </p>
        <p class="mb-0">
            <a href="http://beian.miit.gov.cn/" target="_blank">{{ beian }}</a>&nbsp;|
            <a href=" " target="_blank">Sitemap</a>
            {% if cnzz_protocol %}|&nbsp;{{ cnzz_protocol|safe }}{% endif %}
            <span id="web-day"></span>
        </p>
        <script>function getnewYear(){var d = new Date();var old = new Date('2020/07/28');
            var x = document.getElementById("year-info");
            x.innerHTML=d.getFullYear();var y=document.getElementById("web-day");
            var dd=Math.floor((d.getTime() - old.getTime()) / (24 * 3600 * 1000));
            var d_str="| 网站已续航 "+dd+" 天";y.innerHTML=d_str;}getnewYear()</script>
      </div>
    </div>
</footer>

my_blog/blog/templates/blog/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">

    <!-- 导航栏商标 -->
    <a class="navbar-brand" href="{% url 'blog:index' %}">我的博客</a>

    <!-- 导航入口 -->
    <div>
      <ul class="navbar-nav">
        <!-- 条目 -->
        <li class="nav-item"><a class="nav-link" href="{% url 'blog:index' %}">文章列表</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'blog:article_create' %}">写文章</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'blog:test' %}">测试页面</a></li>
      </ul>
    </div>

  </div>
</nav>

my_blog/blog/templates/blog/index.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "blog/base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}首页{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <div class="row mt-2">

        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <a href="{% url 'blog:detail' article.slug %}" class="btn btn-primary">阅读本文</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock content %}
<!--
<p>我的博客</p>
<p>使用Django搭建的博客网页，记录学习心得、生活感触...</p>
<div class="media mb-1 mb-sm-2 p-2 p-lg-3">
	{% for article in articles %}
		<div class="d-none d-sm-block mb-2 f-15">
		<p>{{ article.title }}</p>
		<p>{{ article.author }} {{ article.create_time }}</p>
		<p>{{ article.summary }}</p>
		<p>{{ article.body|truncatechars_html:450 }}</p>
		</div>
	{% empty %}
		<li>No articles have been added yet.</li>
	{% endfor %}

</div>
-->

my_blog/blog/templates/blog/test.html
{% extends "blog/base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}测试页面{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <div class="row mt-2">
      <p>\n<script type="math/tex; mode=display">3^2</script>\n</p>
      <div>\n<div class="MathJax_Preview">3^2</div>\n<script type="math/tex; mode=display">3^2</script>\n</div>
      <p>A link <a href="https://google.com">https://google.com</a></p>
      <p><span><span class="MathJax_Preview">3^2</span><script type="math/tex">3^2</script></span></p>
    </div>
</div>
{% endblock content %}